version: 2.1

workflows:
  version: 2
  build-and-publish:
    jobs:
      - cache-deps
      - docs:
          requires:
            - cache-deps
      - lint:
          requires:
            - cache-deps
      - test:
          requires:
            - cache-deps
      - test-1-9:
          requires:
            - cache-deps
      - test-1-10:
          requires:
            - cache-deps
      - release:
          context: clj-honeycomb-release
          requires:
            - docs
            - lint
            - test
            - test-1-9
            - test-1-10
          filters:
            branches:
              only: master

jobs:
  cache-deps:
    docker:
      - image: circleci/clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-m2-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          key: v1-m2-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
  docs:
    docker:
      - image: circleci/clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-m2-{{ checksum "project.clj" }}
      - run: lein codox
      - store_artifacts:
          path: target/doc
  lint:
    docker:
      - image: circleci/clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-m2-{{ checksum "project.clj" }}
      - run:
          name: joker --lint
          command: |
            curl -Lso joker.zip https://github.com/candid82/joker/releases/download/v0.11.1/joker-0.11.1-linux-amd64.zip
            unzip joker.zip
            echo '{:known-macros [clojure.spec.alpha/fdef] :rules {:if-without-else true :unused-fn-parameters true}}' > ~/.joker
            find src test -type f -name '*.clj' -print0 | \
              xargs -0 -n1 ./joker --lint
      - run: lein cljfmt check
      - run: lein kibit
  test:
    docker:
      - image: circleci/clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-m2-{{ checksum "project.clj" }}
      - run: lein cloverage --codecov
      - run:
          name: Upload code coverage
          command: |
            bash <(curl -s https://codecov.io/bash)
  test-1-9:
    docker:
      - image: circleci/clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-m2-{{ checksum "project.clj" }}
      - run:
          name: Test with Clojure 1.9
          command: |
            sed -e 's,org.clojure/clojure "1.8.0",org.clojure/clojure "1.9.0",' project.clj > project.clj.new
            mv project.clj.new project.clj
            lein test
  test-1-10:
    docker:
      - image: circleci/clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-m2-{{ checksum "project.clj" }}
      - run:
          name: Test with Clojure 1.10
          command: |
            sed -e 's,org.clojure/clojure "1.8.0",org.clojure/clojure "1.10.0",' project.clj > project.clj.new
            mv project.clj.new project.clj
            lein test
  release:
    docker:
      - image: circleci/clojure
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e1:44:a1:c0:2e:6f:08:ba:11:4e:b7:00:90:38:c3:4c"
      - checkout
      - restore_cache:
          keys:
            - v1-m2-{{ checksum "project.clj" }}
      - run:
          name: Publish the docs to GitHub Pages
          command: |
            git config --global user.email "${CIRCLE_PROJECT_USERNAME}@users.noreply.github.com"
            git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
            git clone -b gh-pages git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git target/doc
            lein codox
            cd target/doc
            git add .
            git commit -m '[CI SKIP] Update documentation'
            git push origin gh-pages
            cd ../..
            git clean -ffdx
      - run: lein deploy
      - run:
          name: Tag the release
          command: |
            git tag "1.0.2.${CIRCLE_BUILD_NUM}"
            git push --tags
