version: 2.1

workflows:
  version: 2
  build-and-publish:
    jobs:
      - cache-deps
      - lint:
          requires:
            - cache-deps
      - test:
          requires:
            - cache-deps

jobs:
  cache-deps:
    docker:
      - image: circleci/clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-m2-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          key: v1-m2-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
  lint:
    docker:
      - image: circleci/clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-m2-{{ checksum "project.clj" }}
      - run: lein cljfmt check
  test:
    docker:
      - image: circleci/clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-m2-{{ checksum "project.clj" }}
      - run: lein cloverage --codecov
      - run:
          name: Upload code coverage
          command: |
            bash <(curl -s https://codecov.io/bash)
